name: CI Pipeline

on:
  workflow_dispatch: # Manual trigger equivalent to 'trigger: none'
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main

jobs:
  build-docker-images:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build API Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./api
          file: ./api/Dockerfile
          push: false
          tags: api:${{ github.run_number }}
          outputs: type=docker,dest=/tmp/api-image.tar

      - name: Build Client Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./client
          file: ./client/Dockerfile
          push: false
          build-args: |
            VITE_API_URL=${{ vars.VITE_API_URL }}
            VITE_CLERK_PUBLISHABLE_KEY=${{ vars.VITE_CLERK_PUBLISHABLE_KEY }}
          tags: client:${{ github.run_number }}
          outputs: type=docker,dest=/tmp/client-image.tar

      - name: Build Landing Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./landing
          file: ./landing/Dockerfile
          push: false
          tags: landing:${{ github.run_number }}
          outputs: type=docker,dest=/tmp/landing-image.tar

      - name: Upload Docker Images
        uses: actions/upload-artifact@v4
        with:
          name: docker-images
          path: /tmp/*-image.tar

  publish-manifest:
    needs: build-docker-images
    runs-on: ubuntu-latest
    
    steps:
      - name: Create Deployment Manifest
        run: |
          echo "Creating deployment manifest for ${{ github.run_number }}"
          cat > deployment.json << EOF
          {
            "version": "${{ github.run_number }}",
            "timestamp": "$(date -u +"%Y-%m-%dT%H:%M:%SZ")",
            "branch": "${{ github.ref_name }}",
            "images": {
              "api": "api:${{ github.run_number }}",
              "client": "client:${{ github.run_number }}",
              "landing": "landing:${{ github.run_number }}"
            },
            "buildPath": {
              "api": "api/dist/api/main.js",
              "client": "client/build",
              "landing": "landing/dist/server"
            },
            "terraform": {
              "providers": ["aws", "azure"]
            }
          }
          EOF
          cat deployment.json

      - name: Upload Deployment Manifest
        uses: actions/upload-artifact@v4
        with:
          name: deployment-manifest
          path: deployment.json
